# こちらのファイルのはいつか修正するべき項目。

# Offense count: 51
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 130

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/*'

# Offense count: 3
Metrics/AbcSize:
  Max: 21

# Offense count: 4
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 22

