# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# メソッド名のprefixに「set_」「get_」を許可
AccessorMethodName:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

# ハッシュのカッコを外さない。そのほうが可読性良いように思う。
Style/BracesAroundHashParameters:
  Enabled: false

# Offense count: 51
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 130

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/*'

# 下記コマンドで自動生成されたやつ
# `rubocop --auto-gen-config --exclude-limit 999999`
# on 2017-10-21 18:35:02 +0900 using RuboCop version 0.36.0.
# The point is for the user to remove these configuration records
# one by one as the offenses are removed from the code base.
# Note that changes in the inspected code, or installation of new
# versions of RuboCop, may require this file to be generated again.

# Offense count: 3
Metrics/AbcSize:
  Max: 21

# Offense count: 1
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 133

# Offense count: 4
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 22

# Offense count: 1
# Configuration parameters: Include.
# Include: app/**/*.rb, config/**/*.rb, db/**/*.rb, lib/**/*.rb
Rails/Output:
  Exclude:
    - 'app/models/qiita_tag.rb'

