Rails:
  Enabled: true

# 違反を一旦無視
  inherit_from: .rubocop_todo.yml

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# メソッド名のprefixに「set_」「get_」を許可
AccessorMethodName:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

# Offense count: 51
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 130

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/*'
