# todoの違反はいつか直すべき違反。
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

Rails:
  Enabled: true

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

# ハッシュのカッコを外さない。そのほうが可読性良いように思う。
Style/BracesAroundHashParameters:
  Enabled: false
