default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: qiita_ranking_development

test:
  <<: *default
  database: qiita_ranking_test

production:
  <<: *default
  database: qiita_ranking_production
